name: gdghunt
description: A application using google play game services
version: 0.1.0
author: Giovanni Laquidara
dependencies:
  googleapis: any
  googleapis_auth: any
  browser: any
  core_elements: ">=0.2.0 <0.3.0"
  polymer: ">=0.12.0 <0.13.0"
  paper_elements: ">=0.1.0 <0.2.0"
transformers:
- polymer:
    entry_points: web/gdghunt.html
  